
# configuration for the app

db:

  host: # your db host url
      null
  user: # database user
      null
  password: # database password
      null
  database: # database name
      null

net:
  port: # port to listen
      null
  host: # url host
      null
  name: # app name
      null

